//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAuth.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTable
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public string EmpDept { get; set; }
        public string EmpMob { get; set; }
        public string EmpAddress { get; set; }
        public Nullable<int> EmpSalary { get; set; }
        public string EmpZender { get; set; }
        public string EmpZip { get; set; }
        public string EmpAbout { get; set; }
    }
}
